#!/bin/bash
# LGSM fn_console function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 210115

# Description: Gives access to the server tmux console.

local modulename="Console"
fn_check_root
fn_check_systemdir
fn_printdots "Starting"
sleep 1
fn_check_tmux
tmuxwc=$(tmux list-sessions 2>&1|awk '{print $1}'|grep -v failed|grep -Ec "^${servicename}:")
if [ "${tmuxwc}" -eq 1 ]; then
	fn_printoknl "Starting"
	sleep 1
	tmux attach-session -t ${servicename}
else
	fn_printfailnl "Server not running"
	sleep 1
	while true; do
		read -p "Do you want to start the server? [y/N]" yn
		case $yn in
		[Yy]* ) fn_start; fn_console; break;;
		[Nn]* ) break;;
		* ) echo "Please answer yes or no.";;
	esac
	done
fi
