#!/bin/bash
# LGSM fn_getopt function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 080214

# Description: getopt arguments.

fn_getopt_generic(){
case "$getopt" in
	start)
		fn_start;;
	stop)
		fn_stop;;
	restart)
		fn_restart;;
	update)
		norestart=1;
		fn_update_check;;
	update-restart)
		fn_update_check;;
	validate)
		fn_validate;;
	validate-restart)
		fn_stop
		fn_validate
		fn_start;;
	monitor)
		fn_monitor;;
	details)
		fn_details;;
	console)
		fn_console;;
	debug)
		fn_debug;;
	install)
		fn_install;;
	auto-install)
		fn_autoinstall;;
	*)
	echo "Usage: $0 {start|stop|restart|update|update-restart|validate|validate-restart|monitor|details|console|debug|install|auto-install}"
	exit 1;;
esac
exit
}

fn_getopt_generic
