#!/bin/bash
# LGSM fn_install function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 080215

fn_check_root
fn_install_header
if [ -z "${autoinstall}" ]; then
	fn_install_serverdir
	fn_install_header
fi
# Download and install
if [ ! -z "${appid}" ]; then
	fn_install_steamcmd
	fn_install_serverfiles
	fn_install_steamfix
fi

# Configuration
fn_install_glibcfix
fn_install_gsquery
fn_install_config
fn_install_complete
