#!/bin/bash
# LGSM fn_monitor function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 080215

# Description: Monitors server by checking for running proccesses
# then passes to fn_monitor_query.

local modulename="Monitor"

fn_monitor_tmux(){
fn_check_root
fn_check_systemdir
fn_check_ip
fn_details_config
fn_printdots "${servername}"
sleep 1
if [ ! -f "${lockselfname}" ]; then
    fn_printinfo "Disabled: No lock file found"
    sleep 1
    echo -en "\n"
    echo "To enable monitor run ${selfname} start"
    exit
fi
updatecheck=$(ps -ef|grep "${selfname} update"|grep -v grep|wc -l)
if [ "${updatecheck}" = "0" ]; then
    fn_printdots "Checking session: CHECKING"
    sleep 1
    tmuxwc=$(tmux list-sessions 2>&1|awk '{print $1}'|grep -v failed|grep -E "^${servicename}:"|wc -l)
    if [ "${tmuxwc}" -eq 1 ]; then
        fn_printok "Checking session: OK"
        sleep 1
        echo -en "\n"
        fn_monitor_query
        exit
    else
        fn_printfail "Checking session: FAIL"
        sleep 1
        echo -en "\n"
        if [ "${emailnotification}" = "on" ]; then
            subject="${servicename} Monitor - Starting ${servername}"
            failurereason="${servicename} process not running"
            actiontaken="${servicename} has been restarted"
            fn_email
        fi
        fn_start
    fi
else
    fn_printinfonl "SteamCMD is currently checking for updates"
    sleep 1
    fn_printinfonl "When update is complete ${servicename} will start"
    sleep 1
fi
}

fn_monitor_tmux
