#!/bin/bash
# LGSM fn_start function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 160214

# Description: Starts the server.

local modulename="Starting"


fn_start_tmux(){
fn_check_root
fn_check_systemdir
fn_check_ip
fn_details_config
fn_parms
fn_printdots "${servername}"
sleep 1
fn_check_tmux
fn_check_steamcmd
tmuxwc=$(tmux list-sessions 2>&1|awk '{print $1}'|grep -v failed|grep -Ec "^${servicename}:")

if [ "${tmuxwc}" -eq 1 ]; then
	fn_printinfo "${servername} is already running"
	sleep 1
	echo -en "\n"
	exit
fi
# Get Over Here
if [ "${getoverhere}" == "yes" ]; then
    fn_printinfo "\nRunning getoverhere ..."
    goh -sc "${rootdir}/serverfiles/tf" metamod sourcemod stripper tf2items accelerator steamtools
fi

# Check For Update
if [ "${updateonstart}" == "yes" ]; then
	fn_update_dl
fi

# Create lock file
date > "${rootdir}/${lockselfname}"
cd "${executabledir}"
tmux new-session -d -s ${servicename} "${executable} ${parms}"

sleep 1
tmuxwc=$(tmux list-sessions 2>&1|awk '{print $1}'|grep -Ec "^${servicename}:")
if [ "${tmuxwc}" -eq 0 ]; then
	fn_printfailnl "Unable to start ${servername}"
	echo -en "	Run debug mode: ./${selfname} debug"

else
	fn_printok "${servername}"
fi
sleep 1
echo -en "\n"
}

fn_start_tmux
